# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827b21749871894bbc58359ab4faf05ce42e24d63d024c69e4f16c4cda52e5d456e1337bd595b482caf4d711c1e5bfeed2e790509ea874d9f4f9a543d1ea47ef

test:
  secret_key_base: d5e648ed19d0ed30bce4979651aa0472beafa9714b0ee7683aaaa7a1f72d3e3badeac0be91051be26dfe84c4f120e32804b92d265bf676603f6bb9f52a9411ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
