# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e349106ac685b6df8f07027c537bfd6bc418bd204731202a71c209bff1f591aac37fae4c4a6019b9739f5c9faec754689471006ae59060498891d8aadda90092

test:
  secret_key_base: 2d6cbf258d99f1417f99edde80df55d7cc3c89239b3b7441b4ce877d4fee7eaa39408dee254d80ac99ae5617b662ae0ec5fd51ab4c36a441072748aa4232d8c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
